# Basic
site_name: BHH Docs
theme:
  language: de
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - content.action.edit
  icon:
    edit: material/github 

  palette: 

    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Zu Dark Mode wechseln

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb-outline
        name: Zu Light Mode wechseln

site_description: Dokumentation für Services die von der Fachschaft Informatik der BHH betrieben werden.

# Repo
repo_name: BHH-Informatik/docs
repo_url: https://github.com/BHH-Informatik/docs
edit_uri: blob/main/docs/

# Copyright
copyright: Copyright &copy; 2024 Fachschaft Informatik der BHH

# Plugins
plugins:
  - git-authors:
      show_email_address: false
      exclude:
        - index.md
  - git-revision-date-localized:
      format: "de_DE"

# Markdown Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

# Navigation
nav:
  - Home: index.md
  #- Fachschaft:
  #  - Über uns: fachschaft/about.md
    #- Kontakt: fachschaft/kontakt.md
  - Services:
    - Mattermost: services/mattermost.md
    - GitLab: services/gitlab.md
    - LimeSurvey: services/limesurvey.md